import {useEffect,useRef,useState} from 'react'
import {Link} from 'react-router-dom'
import {Activity,ArrowRight,BrainCircuit,Check,CheckCircle2,ChevronDown,ClipboardCheck,Clock3,Database,FileHeart,Fingerprint,History,KeyRound,Layers3,LockKeyhole,MapPin,MousePointer2,RefreshCw,ScanLine,ShieldCheck,Smartphone,Stethoscope,UserCheck,Users} from 'lucide-react'
import {Badge,Button,Card} from '../components/ui'

const problems=[
  {icon:FileHeart,no:'01',title:'Bukti CAPD tersebar',text:'Bukti layanan, jadwal pertukaran cairan, dan dokumentasi klinis perlu dicocokkan secara manual.'},
  {icon:RefreshCw,no:'02',title:'Refill PRB berisiko duplikasi',text:'Riwayat pengambilan obat dan periode terapi tidak selalu terlihat dalam satu konteks pemeriksaan.'},
  {icon:MapPin,no:'03',title:'Konflik DPJP sulit terlihat',text:'Pelayanan pada waktu berdekatan di lokasi berbeda dapat terlewat tanpa pemeriksaan lintas data.'}
]
const modules=[
  ['CAPD','Autentikasi bukti layanan','Cocokkan episode, bukti pendukung, dan kronologi layanan.',FileHeart,'Prioritas MVP'],
  ['PRB','Kendali periode refill','Tandai refill terlalu dini, tumpang tindih, atau riwayat yang perlu ditinjau.',RefreshCw,'Prioritas MVP'],
  ['DPJP','Konflik waktu & lokasi','Temukan pola pelayanan yang secara waktu dan lokasi perlu klarifikasi.',MapPin,'Prioritas MVP'],
  ['Rujukan','Konsistensi alur rujukan','Baca kesinambungan asal, tujuan, periode, dan jenis layanan.',ClipboardCheck,'Pengembangan'],
  ['Med. necessity','Konteks kebutuhan medis','Hubungkan diagnosis, tindakan, obat, dan bukti klinis relevan.',Stethoscope,'Pengembangan'],
  ['Audit trail','Jejak keputusan lengkap','Simpan alasan flag, tindakan reviewer, dan perubahan status.',History,'Fondasi']
]
const faqs=[
  ['Apakah Izin Dok memutuskan klaim layak atau tidak?','Tidak. Izin Dok memprioritaskan klaim yang membutuhkan review dan menampilkan alasannya. Keputusan tetap berada pada verifikator berwenang.'],
  ['Apakah ini pengganti sistem BPJS Kesehatan atau SIMRS?','Bukan. Izin Dok dirancang sebagai lapisan workbench pendukung yang dapat melengkapi alur yang sudah ada.'],
  ['Data apa yang digunakan pada prototype ini?','Seluruh identitas, fasilitas, jadwal, dan klaim pada prototype adalah data sintetis—bukan data peserta JKN riil.'],
  ['Mengapa menggunakan deterministic rule dan anomaly signal?','Rule memberi pemeriksaan yang konsisten, sementara anomaly signal membantu menemukan pola tidak biasa. Keduanya diterjemahkan menjadi reason code yang dapat diperiksa manusia.'],
  ['Bagaimana sistem menghindari black-box decision?','Setiap flag menyertakan reason code, data pemicu, konteks pembanding, dan jejak tindakan reviewer.'],
  ['Siapa pengguna utama Izin Dok?','Verifikator klaim, tim kendali mutu dan biaya, fasilitas kesehatan, serta pihak pengelola yang memiliki mandat dan hak akses.'],
  ['Apakah sudah terintegrasi dengan data produksi?','Belum. Tahap saat ini adalah frontend prototype; integrasi, uji keamanan, validasi rule, dan tata kelola data dilakukan pada tahap pilot.'],
  ['Bagaimana rencana penerapannya?','Dimulai dari validasi mockup, prototype dengan data sintetis, pilot terbatas dan terukur, lalu scale setelah evaluasi tata kelola, keamanan, dan dampak.'],
  ['Apakah hasil simulasi merupakan klaim penghematan?','Tidak. Angka dampak di halaman ini adalah skenario ilustratif untuk membantu diskusi desain pilot, bukan hasil implementasi nyata.']
]

function SectionTitle({eyebrow,title,copy,center=false}:{eyebrow:string;title:string;copy?:string;center?:boolean}){return <div className={center?'mx-auto max-w-3xl text-center':'max-w-3xl'}><p className="section-eyebrow">{eyebrow}</p><h2 className="section-title">{title}</h2>{copy&&<p className="section-copy">{copy}</p>}</div>}
function Counter({to,suffix='' }:{to:number;suffix?:string}){const [n,setN]=useState(0);const ref=useRef<HTMLSpanElement>(null);useEffect(()=>{const el=ref.current;if(!el)return;const io=new IntersectionObserver(([e])=>{if(!e.isIntersecting)return;const start=performance.now();const tick=(now:number)=>{const p=Math.min((now-start)/900,1);setN(Math.round(to*(1-Math.pow(1-p,3))));if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick);io.disconnect()},{threshold:.5});io.observe(el);return()=>io.disconnect()},[to]);return <span ref={ref}>{n}{suffix}</span>}
function MiniDashboard({mobile=false}:{mobile?:boolean}){return <div className={mobile?'mx-auto w-[260px] rounded-[2rem] border-[7px] border-navy-950 bg-white p-3 shadow-2xl':'overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl'}><div className={`flex items-center justify-between border-b border-slate-100 ${mobile?'pb-3':'px-5 py-4'}`}><div className="flex items-center gap-2"><span className="grid size-7 place-items-center rounded-lg bg-medical-600 text-white"><Activity size={14}/></span><b className="text-xs text-navy-950">Integrity Queue</b></div><span className="size-2 rounded-full bg-emerald-500"/></div><div className={mobile?'py-3':'grid grid-cols-[145px_1fr]'}>{!mobile&&<div className="space-y-2 bg-navy-950 p-4 text-[11px] text-slate-300"><p className="mb-4 font-bold tracking-wider text-cyan-400">WORKBENCH</p><p className="rounded-lg bg-white/10 p-2 text-white">Risk queue</p><p className="p-2">Evidence</p><p className="p-2">Audit trail</p></div>}<div className={mobile?'':'p-5'}><div className="mb-3 flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-wider text-medical-600">Perlu review</p><b className="text-sm text-navy-950">Klaim prioritas hari ini</b></div><span className="rounded-full bg-amber-50 px-2 py-1 text-[9px] font-bold text-amber-700">7 FLAG</span></div>{[['CAPD-0281','Bukti layanan tidak lengkap','Tinggi'],['PRB-1094','Refill 9 hari lebih awal','Sedang'],['DPJP-0712','Konflik lokasi 32 menit','Tinggi']].slice(0,mobile?2:3).map(([id,risk,level],i)=><div key={id} className="mb-2 rounded-xl border border-slate-200 p-3"><div className="flex items-center justify-between"><b className="text-[11px] text-navy-950">{id}</b><span className={`size-2 rounded-full ${i===1?'bg-amber-400':'bg-red-500'}`}/></div><p className="mt-1 text-[10px] text-slate-500">{risk}</p><div className="mt-2 flex items-center justify-between"><span className="rounded bg-slate-100 px-1.5 py-1 text-[8px] text-slate-500">{level}</span><span className="text-[9px] font-bold text-medical-600">Lihat alasan →</span></div></div>)}</div></div></div>}

export default function Landing(){const [preview,setPreview]=useState<'Desktop'|'Mobile'>('Desktop');return <main>
  <section id="produk" className="hero-grid relative overflow-hidden"><div className="hero-glow"/><div className="mx-auto grid max-w-7xl items-center gap-14 px-5 py-16 lg:grid-cols-[1.03fr_.97fr] lg:py-24"><div className="relative z-10"><Badge tone="blue">EFISIENSI RISIKO FASILITAS KESEHATAN</Badge><h1 className="mt-6 text-5xl font-bold leading-[1.05] tracking-[-.045em] text-navy-950 dark:text-white sm:text-6xl xl:text-7xl">Temukan risiko klaim. <span className="text-medical-600">Pahami alasannya.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600 dark:text-slate-300">Explainable claim-integrity workbench untuk membantu verifikator menemukan klaim yang membutuhkan review—tanpa menggantikan keputusan manusia.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/apps"><Button className="px-6 py-3.5">Buka Aplikasi <ArrowRight size={17}/></Button></Link><Link to="/desktop"><Button className="border border-slate-300 bg-white px-6 py-3.5 text-navy-950 hover:border-medical-600 hover:bg-blue-50">Buka Workbench</Button></Link></div><div className="mt-8 grid max-w-xl grid-cols-3 gap-3 border-t border-slate-200 pt-5 text-xs text-slate-500"><span className="flex items-center gap-1.5"><ScanLine size={14} className="text-medical-600"/> Frontend prototype</span><span className="flex items-center gap-1.5"><Database size={14} className="text-medical-600"/> Data sintetis</span><span className="flex items-center gap-1.5"><UserCheck size={14} className="text-medical-600"/> Human-in-the-loop</span></div></div><div className="relative"><div className="absolute -inset-8 rounded-full bg-cyan-400/10 blur-3xl"/><div className="relative rotate-[1deg]"><MiniDashboard/></div><div className="absolute -bottom-5 -left-3 flex items-center gap-3 rounded-xl border bg-white p-3 shadow-lg"><span className="grid size-9 place-items-center rounded-lg bg-emerald-50 text-emerald-600"><CheckCircle2 size={18}/></span><div><b className="block text-xs text-navy-950">Alasan dapat ditelusuri</b><span className="text-[10px] text-slate-500">Rule → bukti → keputusan</span></div></div></div></div></section>

  <section className="border-y border-slate-200 bg-white px-5 py-5 dark:border-slate-800 dark:bg-slate-900"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-3 text-center md:flex-row md:text-left"><p className="text-sm font-semibold text-navy-950 dark:text-white">Dibangun untuk percakapan integritas klaim yang bertanggung jawab</p><div className="flex flex-wrap justify-center gap-x-7 gap-y-2 text-xs font-medium text-slate-500"><span>BPJS Kesehatan</span><span>Fasilitas Kesehatan</span><span>Tim Verifikasi</span><span>Mitra Teknologi</span></div></div></section>

  <section id="masalah" className="section-wrap"><SectionTitle eyebrow="TIGA TITIK KRITIS MVP" title="Bukan kekurangan data. Masalahnya adalah sinyal penting tersembunyi di antara data." copy="Pemeriksaan manual yang tersebar membuat verifikator menghabiskan waktu untuk mencari konteks, bukan menilai risiko."/><div className="mt-10 grid gap-5 md:grid-cols-3">{problems.map(({icon:I,no,title,text})=><Card key={no} className="group p-6 transition hover:-translate-y-1 hover:border-medical-500 hover:shadow-lg"><div className="flex items-center justify-between"><span className="grid size-11 place-items-center rounded-xl bg-red-50 text-red-600"><I size={21}/></span><span className="text-3xl font-bold text-slate-100 group-hover:text-blue-100">{no}</span></div><h3 className="mt-6 text-lg font-bold text-navy-950 dark:text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></Card>)}</div></section>

  <section id="cara-kerja" className="bg-navy-950 px-5 py-20 text-white"><div className="mx-auto max-w-7xl"><SectionTitle eyebrow="DARI REAKTIF MENJADI TERARAH" title="Review lebih cepat dimulai dari antrean yang lebih cerdas."/><div className="mt-12 grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/5 p-6"><p className="text-xs font-bold tracking-widest text-slate-400">SEBELUM · MANUAL</p><div className="mt-6 space-y-4">{['Buka beberapa sumber dan dokumen','Cocokkan kronologi satu per satu','Mengandalkan temuan individual','Alasan review sulit distandardisasi'].map((x,i)=><div className="flex items-center gap-3 text-sm text-slate-300" key={x}><span className="grid size-7 place-items-center rounded-full bg-white/5 text-xs text-slate-500">{i+1}</span>{x}</div>)}</div></div><div className="relative rounded-2xl border border-cyan-400/30 bg-cyan-400/5 p-6"><span className="absolute right-5 top-5 rounded-full bg-cyan-400/10 px-3 py-1 text-[10px] font-bold text-cyan-300">DENGAN IZIN DOK</span><p className="text-xs font-bold tracking-widest text-cyan-400">SETELAH · TERARAH</p><div className="mt-6 space-y-4">{['Satu antrean berdasarkan tingkat risiko','Reason code menjelaskan setiap flag','Bukti terkait tampil dalam satu konteks','Verifikator tetap memberi keputusan akhir'].map(x=><div className="flex items-center gap-3 text-sm" key={x}><span className="grid size-7 place-items-center rounded-full bg-emerald-400/15 text-emerald-400"><Check size={14}/></span>{x}</div>)}</div></div></div></div></section>

  <section className="section-wrap"><SectionTitle eyebrow="HYBRID, EXPLAINABLE, HUMAN-LED" title="Mesin membantu menyaring. Manusia tetap menilai." copy="Sinyal statistik tidak berdiri sendiri dan rule tidak otomatis menjadi keputusan. Setiap temuan dibawa ke konteks yang dapat diperiksa." center/><div className="engine-flow mt-12">{[[Layers3,'Deterministic rule','Uji aturan yang konsisten'],[BrainCircuit,'Anomaly signal','Soroti pola tidak biasa'],[Fingerprint,'Explainable reason code','Tampilkan pemicu & bukti'],[UserCheck,'Human verification','Konfirmasi oleh petugas']].map(([I,t,d],i)=><div className="engine-step" key={t as string}><span className="engine-icon"><I size={23}/></span><div><b>{t as string}</b><p>{d as string}</p></div>{i<3&&<ArrowRight className="engine-arrow" size={19}/>}</div>)}</div></section>

  <section id="modul" className="bg-slate-100/70 dark:bg-slate-900/50"><div className="section-wrap"><SectionTitle eyebrow="MODUL TERINTEGRASI" title="Mulai dari risiko yang spesifik. Bertumbuh menjadi fondasi integritas."/><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{modules.map(([tag,title,copy,I,status])=><Card key={tag as string} className="group p-5 hover:border-medical-500"><div className="flex items-start justify-between"><span className="grid size-10 place-items-center rounded-xl bg-blue-50 text-medical-600"><I size={20}/></span><span className="text-[9px] font-bold uppercase tracking-wider text-slate-400">{status as string}</span></div><p className="mt-5 text-[10px] font-bold tracking-widest text-medical-600">{tag as string}</p><h3 className="mt-1 font-bold text-navy-950 dark:text-white">{title as string}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{copy as string}</p></Card>)}</div></div></section>

  <section className="section-wrap"><SectionTitle eyebrow="ALUR YANG DAPAT DIAUDIT" title="Satu sinyal, selalu ada jalur penjelasannya." center/><div className="mt-12 flex flex-col items-stretch justify-center gap-3 md:flex-row md:items-center">{[['Input',Database,'Klaim & bukti'],['Risk Engine',BrainCircuit,'Rule + anomaly'],['Reason Code',Fingerprint,'Alasan terstruktur'],['Human Review',UserCheck,'Keputusan petugas']].map(([t,I,d],i)=><div className="contents" key={t as string}><div className="flex-1 rounded-2xl border bg-white p-5 text-center shadow-sm dark:bg-slate-900"><I className="mx-auto text-medical-600" size={25}/><b className="mt-3 block text-sm">{t as string}</b><span className="text-xs text-slate-500">{d as string}</span></div>{i<3&&<ArrowRight className="mx-auto shrink-0 rotate-90 text-slate-300 md:rotate-0"/>}</div>)}</div></section>

  <section id="preview" className="overflow-hidden bg-navy-950 px-5 py-20 text-white"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><p className="section-eyebrow">INTERACTIVE PRODUCT PREVIEW</p><h2 className="section-title text-white">Dari ringkasan risiko ke alasan yang bisa ditindaklanjuti.</h2><p className="section-copy text-slate-300">Workbench desktop membantu verifikator memeriksa antrean. Aplikasi mobile menyiapkan interaksi bukti dari sisi pengguna.</p><div className="mt-7 inline-flex rounded-xl border border-white/10 bg-white/5 p-1">{(['Desktop','Mobile'] as const).map(x=><button key={x} onClick={()=>setPreview(x)} className={`rounded-lg px-5 py-2 text-sm font-semibold ${preview===x?'bg-white text-navy-950':'text-slate-400 hover:text-white'}`}>{x}</button>)}</div><div className="mt-7"><Link to={preview==='Desktop'?'/desktop':'/apps'}><Button>{preview==='Desktop'?'Buka Workbench':'Buka Aplikasi'} <ArrowRight size={16}/></Button></Link></div></div><div className="min-h-[420px] rounded-3xl border border-white/10 bg-white/5 p-4 sm:p-8">{preview==='Desktop'?<MiniDashboard/>:<MiniDashboard mobile/>}</div></div></section>

  <section id="dampak" className="section-wrap"><SectionTitle eyebrow="PERBANDINGAN PROSES" title="Lebih sedikit waktu mencari. Lebih banyak waktu memverifikasi."/><div className="mt-10 overflow-hidden rounded-2xl border border-slate-200 bg-white dark:border-slate-700 dark:bg-slate-900"><div className="grid grid-cols-[1.2fr_1fr_1fr] bg-slate-50 p-4 text-xs font-bold uppercase tracking-wider text-slate-500 dark:bg-slate-800"><span>Tahap</span><span>Proses manual</span><span className="text-medical-600">Dengan Izin Dok</span></div>{[['Prioritas','Urutan masuk / ad hoc','Risk-based queue'],['Pencarian bukti','Buka sumber terpisah','Konteks bukti terpaut'],['Identifikasi masalah','Pemeriksaan satu per satu','Flag + reason code'],['Dokumentasi review','Catatan tidak seragam','Audit trail terstruktur']].map(r=><div key={r[0]} className="grid grid-cols-[1.2fr_1fr_1fr] border-t p-4 text-xs sm:text-sm"><b>{r[0]}</b><span className="text-slate-500">{r[1]}</span><span className="font-medium text-navy-950 dark:text-white">{r[2]}</span></div>)}</div><div className="mt-12 rounded-3xl bg-blue-50 p-7 dark:bg-blue-950/40"><div className="grid gap-7 md:grid-cols-[1.2fr_1fr_1fr_1fr] md:items-center"><div><Badge tone="amber">SIMULASI · BUKAN HASIL IMPLEMENTASI</Badge><h3 className="mt-4 text-xl font-bold">Skenario dampak untuk desain pilot</h3><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">Angka berikut hanya ilustrasi asumsi pada 100 klaim dan harus divalidasi melalui pilot terukur.</p></div>{[[100,'klaim disaring'],[24,'klaim diprioritaskan'],[3,'fokus modul MVP']].map(([v,l])=><div key={l as string} className="border-l border-blue-200 pl-5"><b className="text-4xl text-medical-600"><Counter to={v as number}/></b><p className="mt-1 text-xs text-slate-500">{l as string}</p></div>)}</div></div></section>

  <section id="keamanan" className="bg-slate-100/70 dark:bg-slate-900/50"><div className="section-wrap grid gap-12 lg:grid-cols-[.85fr_1.15fr]"><div><SectionTitle eyebrow="SECURITY BY DESIGN" title="Kepercayaan dibangun sebelum integrasi." copy="Kontrol keamanan dan tata kelola dirancang sebagai bagian dari arsitektur—bukan tambahan di akhir."/><div className="mt-7 flex items-center gap-3 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800"><ShieldCheck size={21}/><b>Tidak ada data peserta JKN riil di prototype.</b></div></div><div className="grid gap-4 sm:grid-cols-2">{[[Database,'Data minimization','Hanya atribut yang relevan untuk tujuan review.'],[Users,'Role access','Akses berbasis peran dan kebutuhan kerja.'],[History,'Audit log','Aktivitas penting tercatat dan dapat ditelusuri.'],[LockKeyhole,'Encryption-ready','Desain siap untuk proteksi data transit dan tersimpan.'],[Clock3,'Retention policy','Masa simpan mengikuti tujuan dan tata kelola.'],[KeyRound,'Controlled integration','Integrasi melalui autentikasi dan kontrol terukur.']].map(([I,t,d])=><div className="rounded-2xl border bg-white p-5 dark:bg-slate-900" key={t as string}><I size={20} className="text-medical-600"/><b className="mt-3 block text-sm">{t as string}</b><p className="mt-1 text-xs leading-5 text-slate-500">{d as string}</p></div>)}</div></div></section>

  <section className="section-wrap"><SectionTitle eyebrow="ROADMAP BERTAHAP" title="Validasi dahulu. Integrasi dengan disiplin." center/><div className="relative mt-12 grid gap-4 md:grid-cols-4"><div className="absolute left-[12%] right-[12%] top-6 hidden h-px bg-blue-200 md:block"/>{[['01','Mockup','Validasi masalah & alur'],['02','Prototype','Data sintetis & usability'],['03','Pilot','Integrasi terbatas & evaluasi'],['04','Scale','Tata kelola & perluasan']].map(([n,t,d],i)=><div className="relative text-center" key={n}><span className={`relative z-10 mx-auto grid size-12 place-items-center rounded-full border-4 border-white text-sm font-bold shadow-sm ${i<2?'bg-medical-600 text-white':'bg-slate-100 text-slate-400'}`}>{n}</span><b className="mt-4 block">{t}</b><p className="mt-1 text-xs text-slate-500">{d}</p></div>)}</div></section>

  <section id="faq" className="bg-white dark:bg-slate-900"><div className="section-wrap grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><SectionTitle eyebrow="FAQ" title="Pertanyaan penting, jawaban yang transparan." copy="Izin Dok memulai dari batasan yang jelas agar kolaborasi dapat dibangun dengan aman."/><div className="divide-y divide-slate-200 border-y border-slate-200 dark:divide-slate-700 dark:border-slate-700">{faqs.map(([q,a],i)=><details key={q} className="group py-1" open={i===0}><summary className="flex cursor-pointer list-none items-center justify-between gap-4 py-4 text-sm font-bold text-navy-950 dark:text-white">{q}<ChevronDown className="shrink-0 transition group-open:rotate-180" size={17}/></summary><p className="max-w-2xl pb-5 pr-8 text-sm leading-6 text-slate-500">{a}</p></details>)}</div></div></section>

  <section className="px-5 py-16"><div className="mx-auto max-w-7xl overflow-hidden rounded-3xl bg-medical-600 px-6 py-12 text-center text-white md:px-12"><MousePointer2 className="mx-auto mb-5 text-cyan-200"/><h2 className="text-3xl font-bold">Lihat bagaimana risiko berubah menjadi alasan.</h2><p className="mx-auto mt-3 max-w-2xl text-sm leading-6 text-blue-100">Jelajahi prototype dengan data sintetis. Tidak ada keputusan klaim otomatis dan tidak ada data peserta JKN riil.</p><div className="mt-7 flex flex-wrap justify-center gap-3"><Link to="/desktop"><Button className="bg-white text-medical-600 hover:bg-blue-50">Buka Workbench <ArrowRight size={16}/></Button></Link><Link to="/apps"><Button className="border border-white/30 bg-transparent hover:bg-white/10"><Smartphone size={16}/> Buka Aplikasi</Button></Link></div></div></section>
</main>}
