import {useEffect,useState} from 'react';
import {Camera,Check,ChevronRight,Download,FileText,HelpCircle,LockKeyhole,MessageSquareWarning,Pill,QrCode,RefreshCw,ShieldCheck,Trash2,UserRound,Users} from 'lucide-react';
import {Badge,Button,Card,Input} from '../components/ui';

type ProofStatus='Tersimpan di perangkat'|'Menunggu sinkronisasi'|'Terkirim dalam simulasi'|'Perlu koreksi';
type Profile={role:'Pasien'|'Caregiver';name:string};
const synthetic={Pasien:'Sari Rahma (Demo)',Caregiver:'Budi Rahma (Demo)'};
const statusTone=(s:ProofStatus)=>s==='Terkirim dalam simulasi'?'green':s==='Perlu koreksi'?'amber':'blue';
function useStored<T>(key:string,initial:T){const [value,setValue]=useState<T>(()=>{try{return JSON.parse(localStorage.getItem(key)!)??initial}catch{return initial}});useEffect(()=>localStorage.setItem(key,JSON.stringify(value)),[key,value]);return [value,setValue] as const}

export function Onboarding({done}:{done:(p:Profile)=>void}){const [step,setStep]=useState(0);const [role,setRole]=useState<'Pasien'|'Caregiver'>('Pasien');const [consent,setConsent]=useState(false);const [pin,setPin]=useState('');const pages=[<div><Badge tone="blue">DEMO AMAN</Badge><h1 className="app-title">Selamat datang di Izin Dok</h1><p className="app-copy">Pendamping perawatan yang sederhana, privat, dan tetap berguna saat koneksi terputus.</p><div className="mt-7 grid gap-3">{(['Pasien','Caregiver'] as const).map(r=><button key={r} onClick={()=>setRole(r)} className={`role-card ${role===r?'selected':''}`}>{r==='Pasien'?<UserRound/>:<Users/>}<span><b>Saya {r}</b><small>{r==='Pasien'?'Kelola perawatan saya':'Dampingi profil sintetis'}</small></span>{role===r&&<Check/>}</button>)}</div></div>,<div><ShieldCheck className="text-medical-600" size={38}/><h1 className="app-title">Privasi di tangan Anda</h1><p className="app-copy">Demo ini hanya memakai profil sintetis. Data dan bukti disimpan lokal di perangkat, dan dapat Anda ekspor atau hapus kapan saja.</p><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>Saya memahami ini adalah simulasi, bukan layanan medis atau keputusan klinis.</span></label>{role==='Caregiver'&&<div className="notice"><LockKeyhole size={18}/>Caregiver dapat membantu pencatatan, tetapi tidak dapat mengubah diagnosis atau keputusan klinis.</div>}</div>,<div><LockKeyhole className="text-medical-600" size={38}/><h1 className="app-title">Kunci lokal opsional</h1><p className="app-copy">Tambahkan 4 digit PIN untuk simulasi perlindungan pada perangkat ini, atau lewati.</p><Input inputMode="numeric" maxLength={4} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,''))} placeholder="••••" className="pin-input"/><small className="block text-center text-slate-400">PIN tidak dikirim ke server.</small></div>];return <div className="onboarding"><div className="stepper">{pages.map((_,i)=><i key={i} className={i<=step?'on':''}/>)}</div>{pages[step]}<div className="mt-auto pt-8"><Button className="w-full py-3" disabled={step===1&&!consent} onClick={()=>step<2?setStep(step+1):done({role,name:synthetic[role]})}>{step===2?'Mulai aplikasi':'Lanjut'}<ChevronRight size={18}/></Button>{step===2&&<button className="skip" onClick={()=>done({role,name:synthetic[role]})}>Lewati PIN</button>}</div></div>}

const Status=({value}:{value:ProofStatus})=><Badge tone={statusTone(value)}>{value}</Badge>;
export default function MobileHome(){const [checked,setChecked]=useStored('izin-capd',[false,false,false,false]);const [proofs,setProofs]=useStored<{name:string,status:ProofStatus}[]>('izin-proofs',[{name:'Foto kantong drainase · 07.15',status:'Terkirim dalam simulasi'},{name:'Catatan tekanan darah · 07.22',status:'Tersimpan di perangkat'}]);const tasks=['Cuci tangan & siapkan area','Catat berat dan tekanan darah','Periksa cairan keluar','Konfirmasi tidak ada keluhan'];const complete=checked.filter(Boolean).length;const addProof=()=>setProofs([{name:`Bukti CAPD · ${new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'})}`,status:navigator.onLine?'Terkirim dalam simulasi':'Menunggu sinkronisasi'},...proofs]);return <div><section className="home-hero"><Badge tone="blue">DATA SINTETIS</Badge><p className="mt-5 text-sm text-cyan-100">Selamat pagi</p><h1 className="text-2xl font-bold">Sari Rahma 👋</h1><Card className="today-card"><div><span className="eyebrow">STATUS LAYANAN HARI INI</span><h2>Terapi berjalan sesuai rencana</h2><p>Sabtu, 29 Agustus · Hari ke-18</p></div><div className="progress-ring">{complete}/4</div></Card></section><section className="app-section"><div className="section-heading"><div><span className="eyebrow">CHECKLIST HARIAN</span><h2>CAPD pagi</h2></div><span>{complete} dari 4</span></div><Card className="checklist">{tasks.map((t,i)=><button key={t} onClick={()=>setChecked(checked.map((v,j)=>j===i?!v:v))}><i className={checked[i]?'done':''}>{checked[i]&&<Check size={15}/>}</i><span>{t}</span></button>)}</Card><button className="scan-card" onClick={addProof}><span><QrCode/><b>Scan QR kantong CAPD</b><small>Kamera simulasi atau masukkan kode manual</small></span><ChevronRight/></button><div className="section-heading mt-7"><h2>Bukti terbaru</h2><button onClick={()=>setProofs(proofs.map(p=>({...p,status:'Terkirim dalam simulasi'})))}><RefreshCw size={14}/> Sinkronkan</button></div><div className="space-y-3">{proofs.map((p,i)=><Card key={i} className="proof"><FileText/><div><b>{p.name}</b><Status value={p.status}/></div></Card>)}</div><p className="safe-note"><ShieldCheck size={16}/> Kamera membantu pencatatan saja dan tidak menjamin pencegahan fraud secara absolut.</p></section></div>}

export function ActivityPage(){const [manual,setManual]=useState('');const [status,setStatus]=useState<ProofStatus>('Tersimpan di perangkat');return <Page title="Aktivitas" subtitle="Bukti dan antrean lokal"><Card className="camera"><Camera size={38}/><b>Simulasi kamera in-app</b><p>Arahkan ke kode QR pada perlengkapan terapi.</p><Button onClick={()=>setStatus(navigator.onLine?'Terkirim dalam simulasi':'Menunggu sinkronisasi')}>Ambil bukti simulasi</Button></Card><label className="field">Fallback kode manual<Input value={manual} onChange={e=>setManual(e.target.value)} placeholder="Contoh: CAPD-DEMO-0829"/></label><Card className="proof"><QrCode/><div><b>{manual||'Bukti baru belum diberi kode'}</b><Status value={status}/></div></Card><Card className="proof"><FileText/><div><b>Foto label kurang jelas</b><Status value="Perlu koreksi"/></div></Card></Page>}
export function TherapyPage(){const [remind,setRemind]=useStored('izin-reminder',true);return <Page title="Terapi" subtitle="Agustus 2026"><div className="notice"><Pill/>Pengingat obat tersimpan lokal pada perangkat.</div><Card className="therapy"><b>Obat bulan berjalan</b>{['Amlodipine 5 mg · 1× sehari','Vitamin B kompleks · 1× sehari','Cairan CAPD · 4× pertukaran'].map((x,i)=><div key={x}><i className={i===0?'active':''}/><span>{x}<small>{i===2?'Perlengkapan terapi':'Sesudah makan'}</small></span></div>)}</Card><label className="toggle-row"><span><b>Pengingat lokal</b><small>Setiap hari pukul 08.00</small></span><input type="checkbox" checked={remind} onChange={e=>setRemind(e.target.checked)}/></label><h2 className="subheading">Riwayat refill</h2>{['12 Agustus 2026 · Selesai','15 Juli 2026 · Selesai'].map(x=><Card className="list-card" key={x}><Pill/><span>{x}</span><Check/></Card>)}</Page>}
export function ReferralPage(){return <Page title="Rujukan" subtitle="Alur layanan berjenjang"><Card className="referral"><span className="eyebrow">RUJUKAN AKTIF</span><h2>RS Sehat Sentosa</h2><p>Poli Penyakit Dalam · Senin, 31 Agustus 2026 · 09.30</p><div><b>Nomor SRB</b><code>SRB-DEMO-260829</code></div><Button><Download size={17}/>Unduh surat kontrol sintetis</Button></Card><h2 className="subheading">Tahapan rujukan</h2>{['Faskes tingkat pertama · Selesai','RS rujukan · Terjadwal','Kontrol lanjutan · Menunggu'].map((x,i)=><div className="timeline" key={x}><i className={i<2?'active':''}/><span>{x}</span></div>)}<Card className="calendar"><b>Kalender appointment</b><div className="cal-grid">{['S','S','R','K','J','S','M',...Array.from({length:31},(_,i)=>String(i+1))].map((x,i)=><span className={x==='31'?'chosen':''} key={i}>{x}</span>)}</div></Card></Page>}
export function AccountPage(){const [font,setFont]=useStored('izin-font','normal');const [contrast,setContrast]=useStored('izin-contrast',false);const [motion,setMotion]=useStored('izin-motion',false);useEffect(()=>{document.documentElement.dataset.font=font;document.documentElement.classList.toggle('high-contrast',contrast);document.documentElement.classList.toggle('reduce-motion',motion)},[font,contrast,motion]);const exportData=()=>{const blob=new Blob([JSON.stringify({...localStorage},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ringkasan-izin-dok-demo.json';a.click()};return <Page title="Akun" subtitle="Sari Rahma · Profil sintetis"><Card className="profile"><div>SR</div><span><b>Sari Rahma</b><small>Pasien demo · data lokal</small></span></Card><h2 className="subheading">Aksesibilitas</h2><label className="field">Ukuran font<select value={font} onChange={e=>setFont(e.target.value)}><option value="normal">Normal</option><option value="large">Besar</option></select></label><Switch label="Kontras tinggi" checked={contrast} set={setContrast}/><Switch label="Kurangi gerakan" checked={motion} set={setMotion}/><h2 className="subheading">Data & bantuan</h2><button className="menu-row"><HelpCircle/>Pusat bantuan<ChevronRight/></button><button className="menu-row"><MessageSquareWarning/>Laporkan masalah<ChevronRight/></button><button className="menu-row" onClick={exportData}><Download/>Export ringkasan data<ChevronRight/></button><button className="menu-row danger" onClick={()=>{if(confirm('Hapus seluruh data lokal?')){localStorage.clear();location.reload()}}}><Trash2/>Hapus seluruh data lokal<ChevronRight/></button><div className="notice mt-5"><ShieldCheck/>Tidak ada data atau foto pasien nyata dalam aplikasi demo ini.</div></Page>}
function Switch({label,checked,set}:{label:string;checked:boolean;set:(x:boolean)=>void}){return <label className="toggle-row"><b>{label}</b><input type="checkbox" checked={checked} onChange={e=>set(e.target.checked)}/></label>}
function Page({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <div className="app-section page"><span className="eyebrow">IZIN DOK</span><h1>{title}</h1><p>{subtitle}</p><div className="page-content">{children}</div></div>}
export function Family(){return <AccountPage/>}
