import { type ButtonHTMLAttributes,type InputHTMLAttributes,type SelectHTMLAttributes,type ReactNode,useEffect,useState } from 'react'
import { ChevronLeft,ChevronRight,Inbox,X } from 'lucide-react'
export const cx=(...v:(string|false|undefined)[])=>v.filter(Boolean).join(' ')
export function Button({className='',children,...p}:ButtonHTMLAttributes<HTMLButtonElement>){return <button className={cx('inline-flex items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold bg-medical-600 text-white hover:bg-medical-500 disabled:opacity-50',className)} {...p}>{children}</button>}
export function Badge({children,tone='blue'}:{children:ReactNode;tone?:'green'|'amber'|'red'|'blue'|'gray'}){const t={green:'bg-emerald-50 text-emerald-700 border-emerald-200 dark:bg-emerald-950',amber:'bg-amber-50 text-amber-700 border-amber-200 dark:bg-amber-950',red:'bg-red-50 text-red-700 border-red-200 dark:bg-red-950',blue:'bg-blue-50 text-blue-700 border-blue-200 dark:bg-blue-950',gray:'bg-slate-50 text-slate-600 border-slate-200 dark:bg-slate-800 dark:text-slate-300'}[tone];return <span className={cx('inline-flex rounded-full border px-2.5 py-1 text-xs font-semibold',t)}>{children}</span>}
export function Card({children,className=''}:{children:ReactNode;className?:string}){return <div className={cx('rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-900',className)}>{children}</div>}
export function Input({className='',...p}:InputHTMLAttributes<HTMLInputElement>){return <input className={cx('w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm outline-none focus:border-medical-500 focus:ring-2 focus:ring-blue-100 dark:border-slate-700 dark:bg-slate-900',className)} {...p}/>}
export function Select({children,...p}:SelectHTMLAttributes<HTMLSelectElement>){return <select className="w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm dark:border-slate-700 dark:bg-slate-900" {...p}>{children}</select>}
export function Alert({children}:{children:ReactNode}){return <div className="rounded-xl border border-blue-200 bg-blue-50 p-3 text-sm text-blue-800 dark:bg-blue-950 dark:text-blue-200">{children}</div>}
export function Tabs({items,active,onChange}:{items:string[];active:string;onChange:(x:string)=>void}){return <div className="flex gap-1 rounded-xl bg-slate-100 p-1 dark:bg-slate-800">{items.map(x=><button key={x} onClick={()=>onChange(x)} className={cx('rounded-lg px-3 py-2 text-sm',active===x&&'bg-white shadow-sm dark:bg-slate-700')}>{x}</button>)}</div>}
export function Modal({open,onClose,title,children}:{open:boolean;onClose:()=>void;title:string;children:ReactNode}){if(!open)return null;return <div className="fixed inset-0 z-50 grid place-items-center bg-navy-950/50 p-4" role="dialog"><Card className="w-full max-w-lg p-5"><div className="mb-4 flex items-center justify-between"><b>{title}</b><button onClick={onClose}><X size={18}/></button></div>{children}</Card></div>}
export function Drawer({open,onClose,children}:{open:boolean;onClose:()=>void;children:ReactNode}){return <div className={cx('fixed inset-0 z-50 bg-black/30 transition',!open&&'pointer-events-none opacity-0')} onClick={onClose}><aside className={cx('ml-auto h-full w-80 bg-white p-5 shadow-xl transition-transform dark:bg-slate-900',!open&&'translate-x-full')} onClick={e=>e.stopPropagation()}>{children}</aside></div>}
export function Tooltip({label,children}:{label:string;children:ReactNode}){return <span className="group relative">{children}<span className="pointer-events-none absolute bottom-full left-1/2 mb-2 hidden -translate-x-1/2 whitespace-nowrap rounded bg-navy-950 px-2 py-1 text-xs text-white group-hover:block">{label}</span></span>}
export function Pagination(){return <div className="flex items-center gap-2"><button aria-label="Sebelumnya" className="rounded-lg border p-2"><ChevronLeft size={16}/></button><span className="text-sm">1 / 4</span><button aria-label="Berikutnya" className="rounded-lg border p-2"><ChevronRight size={16}/></button></div>}
export function EmptyState({title='Belum ada data'}:{title?:string}){return <div className="grid place-items-center gap-2 py-12 text-center text-slate-500"><Inbox size={36}/><b>{title}</b><span className="text-sm">Data akan tampil saat tersedia.</span></div>}
export function Skeleton(){return <div className="animate-pulse space-y-3"><div className="h-8 w-1/3 rounded bg-slate-200"/><div className="h-28 rounded-2xl bg-slate-200"/><div className="h-28 rounded-2xl bg-slate-200"/></div>}
export function Toast({message}:{message:string}){const [show,setShow]=useState(true);useEffect(()=>{const t=setTimeout(()=>setShow(false),3000);return()=>clearTimeout(t)},[]);return show?<div className="fixed bottom-20 right-5 z-50 rounded-xl bg-navy-950 px-4 py-3 text-sm text-white shadow-xl">{message}</div>:null}
export function Table({headers,children}:{headers:string[];children:ReactNode}){return <div className="overflow-auto"><table className="w-full text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase text-slate-500 dark:bg-slate-800"><tr>{headers.map(h=><th key={h} className="px-4 py-3 font-semibold">{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
