import { Activity, Bell, FileCheck2, HeartPulse, Home, Menu, Moon, Search, ShieldCheck, Smartphone, Sun, Users } from 'lucide-react'
import { NavLink,Outlet } from 'react-router-dom'
import { useTheme } from '../lib/theme'
import { Badge,Button,Tooltip } from '../components/ui'
const Logo=({compact=false}:{compact?:boolean})=><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-xl bg-medical-600 text-white"><Activity size={20}/></div>{!compact&&<div><div className="text-[10px] font-bold tracking-[.2em] text-medical-600">MEDAI NEXUS</div><b className="text-base">Izin Dok</b></div>}</div>
export function PublicLayout(){const {dark,toggle}=useTheme();return <div className="min-h-screen"><header className="sticky top-0 z-40 border-b border-slate-200/80 bg-white/95 dark:border-slate-800 dark:bg-navy-950/95"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><Logo/><nav className="hidden items-center gap-7 text-sm font-medium md:flex"><a href="#solusi">Solusi</a><a href="#prinsip">Prinsip</a><a href="#keamanan">Keamanan</a></nav><div className="flex items-center gap-2"><button onClick={toggle} className="rounded-xl border p-2.5" aria-label="Ganti tema">{dark?<Sun size={18}/>:<Moon size={18}/>}</button><NavLink to="/apps"><Button>Coba simulasi</Button></NavLink></div></div></header><Outlet/><footer className="border-t px-5 py-8 text-center text-sm text-slate-500">© 2026 MEDAI NEXUS · Izin Dok · Seluruh data adalah sintetis</footer></div>}
const desktopNav=[['Ringkasan','/desktop',Home],['Klaim','/desktop/claims',FileCheck2],['Evidence','/desktop/evidence',ShieldCheck],['Pasien','/desktop/patients',Users]] as const
export function DesktopLayout(){const {dark,toggle}=useTheme();return <div className="flex min-h-screen bg-slate-50 dark:bg-navy-950"><aside className="fixed inset-y-0 left-0 hidden w-64 border-r bg-white p-5 dark:border-slate-800 dark:bg-slate-900 lg:block"><Logo/><div className="mt-8"><Badge tone="blue">SIMULASI · DATA SINTETIS</Badge></div><nav className="mt-7 space-y-1">{desktopNav.map(([n,to,I])=><NavLink key={n} to={to} end={to==='/desktop'} className={({isActive})=>`flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-medium ${isActive?'bg-blue-50 text-medical-600 dark:bg-blue-950':'text-slate-500 hover:bg-slate-50 dark:hover:bg-slate-800'}`}><I size={18}/>{n}</NavLink>)}</nav><div className="absolute bottom-5 left-5 right-5 rounded-xl bg-slate-50 p-3 text-xs text-slate-500 dark:bg-slate-800">Demo workspace<br/><b className="text-slate-700 dark:text-white">RS Sehat Sentosa</b></div></aside><main className="min-w-0 flex-1 lg:ml-64"><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b bg-white px-5 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-3"><Menu className="lg:hidden"/><div className="hidden items-center gap-2 rounded-xl bg-slate-100 px-3 py-2 text-slate-500 sm:flex"><Search size={17}/><span className="text-sm">Cari klaim, pasien sintetis...</span><kbd className="ml-8 text-xs">⌘ K</kbd></div></div><div className="flex items-center gap-3"><Tooltip label="Ganti tema"><button onClick={toggle}>{dark?<Sun size={19}/>:<Moon size={19}/>}</button></Tooltip><Bell size={19}/><div className="grid size-9 place-items-center rounded-full bg-cyan-100 text-sm font-bold text-cyan-800">DR</div></div></header><div className="p-5 lg:p-8"><Outlet/></div></main></div>}
export function MobileLayout(){return <div className="mx-auto min-h-screen max-w-lg bg-slate-50 shadow-xl dark:bg-navy-950"><header className="flex items-center justify-between bg-navy-950 px-5 py-4 text-white"><Logo/><Bell size={20}/></header><main className="pb-24"><Outlet/></main><nav className="fixed bottom-0 left-1/2 z-30 flex w-full max-w-lg -translate-x-1/2 justify-around border-t bg-white px-2 py-2 dark:border-slate-800 dark:bg-slate-900">{[['Beranda','/apps',Home],['Dokumen','/apps/documents',FileCheck2],['Keluarga','/apps/family',Users],['Profil','/apps/profile',Smartphone]].map(([n,to,I])=><NavLink key={n as string} to={to as string} end={to==='/apps'} className={({isActive})=>`flex flex-col items-center gap-1 rounded-lg px-3 py-1 text-[11px] ${isActive?'text-medical-600':'text-slate-400'}`}><I size={20}/>{n as string}</NavLink>)}</nav></div>}
export {Logo}
